/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: 642b18326af6019bfd81b1a92af84a40
// flow-typed version: <<STUB>>/eslint-config-react-app_v^2.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-react-app/index' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
declare module 'eslint-config-react-app/index.js' {
  declare module.exports: $Exports<'eslint-config-react-app'>;
}
