/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: 962854c425a5b006330206cc5697ceb9
// flow-typed version: <<STUB>>/extract-text-webpack-plugin_v3.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-text-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-text-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-text-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/ExtractedModule' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/ExtractTextPluginCompilation' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/helpers' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/OrderUndefinedError' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-text-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/cjs'>;
}
declare module 'extract-text-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/index'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/ExtractedModule.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/ExtractedModule'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/ExtractTextPluginCompilation.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/ExtractTextPluginCompilation'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/helpers.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/helpers'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/OrderUndefinedError.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/OrderUndefinedError'>;
}
declare module 'extract-text-webpack-plugin/dist/loader.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/loader'>;
}
