/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: e03e09f5b09e8fa7fe9a359800c22ac4
// flow-typed version: <<STUB>>/flow-coverage-report_v^0.5.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-coverage-report'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-coverage-report' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-coverage-report/bin/flow-coverage-report' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/cli/args' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/cli/config' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/cli/index' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/body-coverage-sourcefile' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/body-coverage-summary' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/coverage-file-table-head' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/coverage-file-table-row' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/coverage-meter-bar' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/coverage-summary-table' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/footer' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/head' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/components/html-report-page' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/flow' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/index' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/promisified' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/report-badge' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/report-html' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/report-json' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/dist/lib/report-text' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/cli/args' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/cli/config' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/cli/index' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/body-coverage-sourcefile' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/body-coverage-summary' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/coverage-file-table-head' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/coverage-file-table-row' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/coverage-meter-bar' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/coverage-summary-table' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/footer' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/head' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/components/html-report-page' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/flow' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/index' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/promisified' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/report-badge' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/report-html' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/report-json' {
  declare module.exports: any;
}

declare module 'flow-coverage-report/src/lib/report-text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-coverage-report/bin/flow-coverage-report.js' {
  declare module.exports: $Exports<'flow-coverage-report/bin/flow-coverage-report'>;
}
declare module 'flow-coverage-report/dist/lib/cli/args.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/cli/args'>;
}
declare module 'flow-coverage-report/dist/lib/cli/config.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/cli/config'>;
}
declare module 'flow-coverage-report/dist/lib/cli/index.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/cli/index'>;
}
declare module 'flow-coverage-report/dist/lib/components/body-coverage-sourcefile.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/body-coverage-sourcefile'>;
}
declare module 'flow-coverage-report/dist/lib/components/body-coverage-summary.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/body-coverage-summary'>;
}
declare module 'flow-coverage-report/dist/lib/components/coverage-file-table-head.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/coverage-file-table-head'>;
}
declare module 'flow-coverage-report/dist/lib/components/coverage-file-table-row.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/coverage-file-table-row'>;
}
declare module 'flow-coverage-report/dist/lib/components/coverage-meter-bar.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/coverage-meter-bar'>;
}
declare module 'flow-coverage-report/dist/lib/components/coverage-summary-table.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/coverage-summary-table'>;
}
declare module 'flow-coverage-report/dist/lib/components/footer.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/footer'>;
}
declare module 'flow-coverage-report/dist/lib/components/head.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/head'>;
}
declare module 'flow-coverage-report/dist/lib/components/html-report-page.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/components/html-report-page'>;
}
declare module 'flow-coverage-report/dist/lib/flow.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/flow'>;
}
declare module 'flow-coverage-report/dist/lib/index.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/index'>;
}
declare module 'flow-coverage-report/dist/lib/promisified.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/promisified'>;
}
declare module 'flow-coverage-report/dist/lib/report-badge.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/report-badge'>;
}
declare module 'flow-coverage-report/dist/lib/report-html.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/report-html'>;
}
declare module 'flow-coverage-report/dist/lib/report-json.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/report-json'>;
}
declare module 'flow-coverage-report/dist/lib/report-text.js' {
  declare module.exports: $Exports<'flow-coverage-report/dist/lib/report-text'>;
}
declare module 'flow-coverage-report/src/lib/cli/args.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/cli/args'>;
}
declare module 'flow-coverage-report/src/lib/cli/config.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/cli/config'>;
}
declare module 'flow-coverage-report/src/lib/cli/index.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/cli/index'>;
}
declare module 'flow-coverage-report/src/lib/components/body-coverage-sourcefile.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/body-coverage-sourcefile'>;
}
declare module 'flow-coverage-report/src/lib/components/body-coverage-summary.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/body-coverage-summary'>;
}
declare module 'flow-coverage-report/src/lib/components/coverage-file-table-head.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/coverage-file-table-head'>;
}
declare module 'flow-coverage-report/src/lib/components/coverage-file-table-row.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/coverage-file-table-row'>;
}
declare module 'flow-coverage-report/src/lib/components/coverage-meter-bar.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/coverage-meter-bar'>;
}
declare module 'flow-coverage-report/src/lib/components/coverage-summary-table.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/coverage-summary-table'>;
}
declare module 'flow-coverage-report/src/lib/components/footer.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/footer'>;
}
declare module 'flow-coverage-report/src/lib/components/head.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/head'>;
}
declare module 'flow-coverage-report/src/lib/components/html-report-page.jsx' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/components/html-report-page'>;
}
declare module 'flow-coverage-report/src/lib/flow.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/flow'>;
}
declare module 'flow-coverage-report/src/lib/index.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/index'>;
}
declare module 'flow-coverage-report/src/lib/promisified.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/promisified'>;
}
declare module 'flow-coverage-report/src/lib/report-badge.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/report-badge'>;
}
declare module 'flow-coverage-report/src/lib/report-html.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/report-html'>;
}
declare module 'flow-coverage-report/src/lib/report-json.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/report-json'>;
}
declare module 'flow-coverage-report/src/lib/report-text.js' {
  declare module.exports: $Exports<'flow-coverage-report/src/lib/report-text'>;
}
