/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: 590e89dd882132a8fd3edc709b42e691
// flow-typed version: <<STUB>>/html-webpack-plugin_v2.29.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-webpack-plugin/lib/chunksorter' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/compiler' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/errors' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-webpack-plugin/index' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/lib/chunksorter.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/chunksorter'>;
}
declare module 'html-webpack-plugin/lib/compiler.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/compiler'>;
}
declare module 'html-webpack-plugin/lib/errors.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/errors'>;
}
declare module 'html-webpack-plugin/lib/loader.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/loader'>;
}
