/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: 8e10b6e5179d164cba06cfab76480531
// flow-typed version: <<STUB>>/postcss-loader_v2.0.6/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-loader/lib/Error' {
  declare module.exports: any;
}

declare module 'postcss-loader/lib/index' {
  declare module.exports: any;
}

declare module 'postcss-loader/lib/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-loader/lib/Error.js' {
  declare module.exports: $Exports<'postcss-loader/lib/Error'>;
}
declare module 'postcss-loader/lib/index.js' {
  declare module.exports: $Exports<'postcss-loader/lib/index'>;
}
declare module 'postcss-loader/lib/options.js' {
  declare module.exports: $Exports<'postcss-loader/lib/options'>;
}
