/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: 8ba2705e527c132c96f3dd49113182e0
// flow-typed version: <<STUB>>/prettier-eslint-cli_v^4.3.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-eslint-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-eslint-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-eslint-cli/dist/add-exception-handler' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/argv' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/format-files' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/index' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/messages' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/no-main' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/parser' {
  declare module.exports: any;
}

declare module 'prettier-eslint-cli/dist/uncaught-exception-handler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-eslint-cli/dist/add-exception-handler.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/add-exception-handler'>;
}
declare module 'prettier-eslint-cli/dist/argv.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/argv'>;
}
declare module 'prettier-eslint-cli/dist/format-files.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/format-files'>;
}
declare module 'prettier-eslint-cli/dist/index.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/index'>;
}
declare module 'prettier-eslint-cli/dist/messages.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/messages'>;
}
declare module 'prettier-eslint-cli/dist/no-main.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/no-main'>;
}
declare module 'prettier-eslint-cli/dist/parser.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/parser'>;
}
declare module 'prettier-eslint-cli/dist/uncaught-exception-handler.js' {
  declare module.exports: $Exports<'prettier-eslint-cli/dist/uncaught-exception-handler'>;
}
