/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: 64d3df9f6fb2911148f194eeeabd313a
// flow-typed version: <<STUB>>/react-hot-loader_vnext/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hot-loader/babel' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/babel.development' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/babel.production.min' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/react-hot-loader.development' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/react-hot-loader.production.min' {
  declare module.exports: any;
}

declare module 'react-hot-loader/patch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hot-loader/babel.js' {
  declare module.exports: $Exports<'react-hot-loader/babel'>;
}
declare module 'react-hot-loader/dist/babel.development.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/babel.development'>;
}
declare module 'react-hot-loader/dist/babel.production.min.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/babel.production.min'>;
}
declare module 'react-hot-loader/dist/react-hot-loader.development.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/react-hot-loader.development'>;
}
declare module 'react-hot-loader/dist/react-hot-loader.production.min.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/react-hot-loader.production.min'>;
}
declare module 'react-hot-loader/index' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/index.js' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/patch.js' {
  declare module.exports: $Exports<'react-hot-loader/patch'>;
}
