/*
 * Copyright 2018 Tiarê Balbi Bonamini
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// flow-typed signature: 333a4f265b6c5a177d0407221beeb304
// flow-typed version: <<STUB>>/style-loader_v0.18.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-loader/lib/addStyles' {
  declare module.exports: any;
}

declare module 'style-loader/lib/addStyleUrl' {
  declare module.exports: any;
}

declare module 'style-loader/lib/urls' {
  declare module.exports: any;
}

declare module 'style-loader/url' {
  declare module.exports: any;
}

declare module 'style-loader/useable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-loader/index' {
  declare module.exports: $Exports<'style-loader'>;
}
declare module 'style-loader/index.js' {
  declare module.exports: $Exports<'style-loader'>;
}
declare module 'style-loader/lib/addStyles.js' {
  declare module.exports: $Exports<'style-loader/lib/addStyles'>;
}
declare module 'style-loader/lib/addStyleUrl.js' {
  declare module.exports: $Exports<'style-loader/lib/addStyleUrl'>;
}
declare module 'style-loader/lib/urls.js' {
  declare module.exports: $Exports<'style-loader/lib/urls'>;
}
declare module 'style-loader/url.js' {
  declare module.exports: $Exports<'style-loader/url'>;
}
declare module 'style-loader/useable.js' {
  declare module.exports: $Exports<'style-loader/useable'>;
}
